{"Doctor_Name": "Dr. Patrick Donovan, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Robert Brooks, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Frederick Jaeger, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Nika Lustgarten, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Joann Miller, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Gregory Sobczak, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Edward Stepanenkov, DMD", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Elizabeth Reiser-Loeber, DMD", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Christopher Gilbert, DMD", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Kendra Schaefer, DMD", "Gender": "Female", "Speciality": "Prosthodontics"}
{"Doctor_Name": "Dr. Patrick Elliott, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. David Walther, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Sarah Squires, DMD", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Christine Julian-Hoernke, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Martin Challenger, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. David Niles, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Matthew Kutz, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. James Hill, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Thomas Reid, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Michael Reese, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Brian Porter, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Stuart McCormick, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Gary Ries, DMD", "Gender": "Male", "Speciality": "Endodontics"}
{"Doctor_Name": "Dr. Kelly Beck, DDS", "Gender": "Female", "Speciality": "Prosthodontics"}
{"Doctor_Name": "Dr. Edwin Batchelor, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Brittany Bowen, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Charles Rubash, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Amy Sergeant, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Bryan Wierwill, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Nicholas Anders, DDS", "Gender": "Male", "Speciality": "Endodontics"}
{"Doctor_Name": "Dr. Patricia Richardson, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Brett Veerman, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Daniel O'Brien, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Donald Tipple, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. David Allen, DDS", "Gender": "Male", "Speciality": "Orthodontics & Dentofacial Orthopedics"}
{"Doctor_Name": "Dr. Seyed Hosseini, DDS", "Gender": "", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Gary Conger, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Craig Madsen, DDS", "Gender": "Male", "Speciality": "Prosthodontics"}
{"Doctor_Name": "Dr. Tamim Sifri, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Kathryn Giswold, DDS", "Gender": "Female", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Wing-Kai Cheung, DDS", "Gender": "Male", "Speciality": "Dentistry"}
{"Doctor_Name": "Dr. Thomas Wenham, DMD", "Gender": "Male", "Speciality": "Orthodontics & Dentofacial Orthopedics"}
